name: Run API and UI Tests

on:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Step 3: Install Playwright dependencies
    - name: Install Playwright dependencies
      run: |
        npx playwright install-deps
        dotnet tool install --global Microsoft.Playwright.CLI
        cd "API TestExercise"
        dotnet add package Microsoft.Playwright

    # Step 4: Restore .NET dependencies
    - name: Restore .NET dependencies
      run: dotnet restore "API TestExercise/NASAapiTestSolution.sln"

    # Step 5: Build solution
    - name: Build solution
      run: dotnet build "API TestExercise/NASAapiTestSolution.sln"

    # Step 6: Install Playwright browsers
    - name: Install Playwright browsers
      run: |
        cd "API TestExercise"
        playwright install

    # Step 7: Run API and UI tests
    - name: Run tests
      env:
        HEADLESS: "true"
      run: dotnet test "API TestExercise/NASAapiTestSolution.sln" --settings:"API TestExercise/.runsettings"